sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t wazzadevli0/docker_kube_udemy -f Dockerfile.dev .
script:
  - docker run -e CI=true wazzadevli0/docker_kube_udemy npm run test
